Completed `1.5 Conversions, casting and dereferencing`
staedoix/rust-incubator pull request #5
Opened 2023-10-12 12:56 UTC by staedoix

2023-10-16 15:36 UTC, evdokimovs requested changes

2023-10-16 15:36 UTC, evdokimovs commented on 1_concepts/1_5_convert_cast_deref/src/main.rs
> +struct Random<T>(Box<T>, Box<T>, Box<T>);
Можете объяснить зачем здесь нужен `Box`?

2023-10-17 13:29 UTC, staedoix commented on 1_concepts/1_5_convert_cast_deref/src/main.rs
> +struct Random<T>(Box<T>, Box<T>, Box<T>);
В задании попросили написать умный указатель, поэтому я использовал `Box`, чтобы гарантировать, что `Random` владеет значениями и очистит память при дропе. Если же использовать не `Box`, а, к примеру, простые значения `T` , то `Random` нельзя будет считать умным указателем.

2023-10-18 22:02 UTC, evdokimovs commented on 1_concepts/1_5_convert_cast_deref/src/main.rs
> +struct Random<T>(Box<T>, Box<T>, Box<T>);
В задании подразумевается, что `Random` сам по себе самописный смарт поинтер. Для того, чтобы быть смарт поинтером ему не нужно под капотом использовать какой-то другой смарт поинтер.

2023-10-19 20:39 UTC, evdokimovs requested changes

2023-10-19 20:39 UTC, evdokimovs commented on 1_concepts/1_5_convert_cast_deref/src/main.rs
> +            *(ptr.as_ptr()) = [
`unsafe` код в этом задании не имеет смысла. Достаточно просто `struct Random<T>(T)`.

2023-10-23 20:05 UTC, evdokimovs approved these changes

2023-10-24 12:00 UTC, merged